import Head from "next/head";
import { Poppins } from "next/font/google";

import BackgroundWallpaper from "@/components/BackgroundWallpaper";
import ContainerInfo from "@/components/ContainerInfo";
import BoxLogin from "@/components/BoxLogin";
import { FormProvider } from "@/context/FormContext";
import FormTeamSelect from "@/components/FormTeamSelect";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Meu Time</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${poppins.className}`}>
        <FormProvider>
          <BackgroundWallpaper />
          <ContainerInfo />
          <BoxLogin />
          <FormTeamSelect />
        </FormProvider>
      </main>
    </>
  );
}
